import type { Tab, TaskForm } from '@/types/care';

export const patientId = '00000000-0000-0000-0000-000000000001';
export const formatDate = (value: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value));
export const formatTime = (value: string) => new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(value));
export const formatDateTime = (value: string) => `${formatDate(value)} · ${formatTime(value)}`;
export const dateInputValue = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
export const initialTaskForm = (): TaskForm => ({ taskType: 'medication', medicationName: '', dosage: '', instructions: '', dueAt: dateInputValue(new Date(Date.now() + 86_400_000)) });
export const tabHeadings: Record<Tab, { title: string; sub: string }> = {
  overview: { title: 'Good morning, Elena', sub: 'Keep Maya’s recovery moving with a clear view of what needs attention.' },
  'care-plans': { title: 'Care plans', sub: 'Manage every task assigned to Maya and track completion.' },
  alerts: { title: 'Alerts', sub: 'Review exceptions generated by patient responses that need attention.' },
  timeline: { title: 'Timeline', sub: 'A complete chronological view of Maya’s care activity.' },
};
export const getInitialTheme = (): 'light' | 'dark' => 'light';
